apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-ev
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: carlodiazpor/backend-ev:1.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef: { name: backend-config }
            - secretRef: { name: backend-secret }